# Generated by Django 5.0.2 on 2024-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='data_ocorrido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
