# Generated by Django 5.0.2 on 2024-02-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_denuncia_data_ocorrido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='acoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='testemunhas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
