# Generated by Django 5.0.2 on 2024-04-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_denuncia_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
