# Generated by Django 5.0.2 on 2024-04-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_denuncia_evidencias_evidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='denuncia_images'),
        ),
    ]
