# Generated by Django 5.0.2 on 2024-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_evidencia_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='evidencias',
        ),
        migrations.DeleteModel(
            name='Evidencia',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='evidencias',
            field=models.ImageField(blank=True, null=True, upload_to='denuncia_images'),
        ),
    ]
