# Generated by Django 5.0.2 on 2024-04-30 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_denuncia_evidencias_delete_evidencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='evidencias',
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='denuncia_images')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.denuncia')),
            ],
        ),
    ]
