# Generated by Django 5.0.2 on 2024-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('endereco_empresa', models.CharField(max_length=255)),
                ('tipo_denuncia', models.CharField(choices=[('ASSEDIO', 'ASSÉDIO (MORAL, SEXUAL, ETC.)'), ('DISCRIMINACAO', 'DISCRIMINAÇÃO (RAÇA, GÊNERO, IDADE, ETC.)'), ('VIOLACAO', 'VIOLAÇÕES DE POLÍTICAS DA EMPRESA'), ('SEGURANCA', 'QUESTÕES DE SEGURANÇA NO TRABALHO'), ('OUTROS', 'OUTRAS QUESTÕES ESPECÍFICAS')], max_length=13)),
                ('decricao', models.TextField()),
                ('testemunhas', models.CharField(max_length=255)),
                ('acoes', models.CharField(max_length=255)),
                ('anonimo', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('data_ocorrido', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
