# Generated by Django 5.0.2 on 2024-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='evidencias',
            field=models.ImageField(blank=True, null=True, upload_to='denuncia_images'),
        ),
    ]
